### ISSUE TITLE
msys-2.0.dll was not found

### ISSUE THREAD

**Issue by titanofold** [nobiot/emacsql-sqlite.exe#2]
Thank you so much for doing this!

Unfortunately, I'm not able to build/install msys on my machine either.

Could you include the DLLs, too? Or, perhaps link directly to where I could download the DLL.

Program error from emacsql-sqlite.exe:

    The code excution cannot proceed because msys-2.0.dll was not found. Reinstalling the program may fix this problem.

**Comment by nobiot** [comment]
Have you installed msys2?

**Comment by nobiot** [comment]
Or are you talking about the compiled .exe file? sorry i am missing the context.

**Comment by nobiot** [comment]
I compiled the executable in a different way.

This time I followed [this](https://www.davidegrayson.com/windev/msys2/).
It should not require `msys2.dll`.

The file now have different hash and length as below.
    SHA256: E3589CFD5836C07971AE2EFB8137891C07AD747C0012C75ED058EA693D190502
    Length: 1613868
    Name: emacsql-sqlite.exe

It's working on my machine -- I replaced my executable with this new one.

**Comment by titanofold** [comment]
E3589CFD works for me, too!

This is on a work machine that I have very little rights to do anything on, so installing libraries.

Thank you so much for figuring this out!

**Comment by nobiot** [comment]
Thank you for confirming that the new binary works for you :)
